services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - kafka
  consumer:
    build: .
    command: python -u routers/consumer.py
    depends_on:
      - kafka
      - web
    volumes:
      - .:/app
    environment:
      - SENDER_EMAIL=officialgigabyte2006@gmail.com
      - APP_PASSWORD=uzcd aikb qvxw crji
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: API_project
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1